language: ruby
rvm:
  - 2.0.0
jdk:
  - oraclejdk8
install:
  - mkdir /tmp/dynamodb
  - wget -O - https://s3-ap-northeast-1.amazonaws.com/dynamodb-local-tokyo/dynamodb_local_latest.tar.gz | tar xz --directory /tmp/dynamodb
  - bundle install --jobs=3 --retry=3 --path vendor/bundle
bundler_args: --deployment
cache: bundler
before_script:
  - java -Xms1024m -Xmx1024m -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/DynamoDBLocal.jar &
  - sleep 4
